version: '3.8'

services:
  registry-server:
    build:
      context: ./agrohub-discovery-service
      dockerfile: Dockerfile
    container_name: eureka_server_container
    ports:
      - "8761:8761"
    environment:
      REGISTRY_URL: ${REGISTRY_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - app_network
      
  producers-db:
    image: postgres:16-alpine
    container_name: agrohub_producers_db
    environment:
      POSTGRES_DB: agrohub_producers_db
      POSTGRES_USER: agrohub_user
      POSTGRES_PASSWORD: agrohub_password
    ports:
      - "5432:5432"
    volumes:
      - producers_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agrohub_user -d agrohub_producers_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
      
  catalog-db:
    image: postgres:16-alpine
    container_name: agrohub_catalog_db
    environment:
      POSTGRES_DB: agrohub_catalog_db
      POSTGRES_USER: agrohub_user
      POSTGRES_PASSWORD: agrohub_password
    ports:
      - "5433:5432"
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agrohub_user -d agrohub_catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  producers_db_data:
  catalog_db_data:

networks:
  app_network:
    driver: bridge