server:
  port: 8761

spring:
  application:
    name: registry-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${REGISTRY_URL:http://localhost:8761/eureka/}
  instance:
    hostname: registry-server